(self.AMP=self.AMP||[]).push({n:"amp-auto-lightbox",v:"1905291911450",f:(function(AMP,_){
(function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a})(this);function h(){var a,c;this.promise=new Promise(function(b,d){a=b;c=d});this.resolve=a;this.reject=c}function k(a){return new Promise(function(c){c(a())})};function l(a,c){c=void 0===c?"":c;try{return decodeURIComponent(a)}catch(b){return c}};var m=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function n(a){var c=Object.create(null);if(!a)return c;for(var b;b=m.exec(a);){var d=l(b[1],b[1]),e=b[2]?l(b[2],b[2]):"";c[d]=e}return c};var p="";
function r(a){var c=a||self;if(c.AMP_MODE)var b=c.AMP_MODE;else{b=c;var d=self.AMP_CONFIG||{},e=!!d.test||!1,f=b.__karma__&&b.__karma__.config.amp.testOnIe,g=n(b.location.originalHash||b.location.hash);d=d.spt;var q=n(b.location.search);p||(p=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"011905291911450");b=c.AMP_MODE={localDev:!1,development:!("1"!=g.development&&!b.AMP_DEV_MODE),examiner:"2"==g.development,filter:g.filter,geoOverride:g["amp-geo"],minified:!0,lite:void 0!=q.amp_lite,test:e,testIe:f,
log:g.log,version:"1905291911450",rtvVersion:p,singlePassType:d}}return b};function t(a){return a?Array.prototype.slice.call(a):[]};self.log=self.log||{user:null,dev:null,userForEmbed:null};var u=self.log;function v(){if(u.dev)return u.dev;throw Error("failed to call initLogConstructor");};function w(a,c){var b,d=a.ownerDocument.defaultView,e=d!=(d.__AMP_TOP||d);if(e){if(x(d,c)){var f=y(d,c);if(f)return f}if(!b)return null}a=z(a);a=A(a);return x(a,c)?y(a,c):null}function B(a,c){a=a.__AMP_TOP||a;return y(a,c)}function z(a){return a.nodeType?B((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function A(a){a=z(a);return a.isSingleDoc()?a.win:a}
function y(a,c){x(a,c);var b=a.services;b||(b=a.services={});var d=b;a=d[c];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function x(a,c){a=a.services&&a.services[c];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function C(a,c){for(var b;a&&a!==b;a=a.parentElement)if(c(a))return a;return null}function D(a){return a.closest?a.closest("a[href],amp-script,amp-story,button,amp-lightbox,amp-carousel,[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option],[subscriptions-action]"):C(a,function(a){return E(a,"a[href],amp-script,amp-story,button,amp-lightbox,amp-carousel,[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option],[subscriptions-action]")})}
function E(a,c){var b=a.matches||a.webkitMatchesSelector||a.mozMatchesSelector||a.msMatchesSelector||a.oMatchesSelector;return b?b.call(a,c):!1}function F(a,c){for(var b=a.length,d=0;d<b;d++)c(a[d],d)}function G(a){if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var c=new h;a.__AMP_UPG_PRM=c.promise;a.__AMP_UPG_RES=c.resolve}return a.__AMP_UPG_PRM};/nochunking=1/.test(self.location.hash);Promise.resolve();(function(a){return a||{}})({c:!0,v:!0,a:!0,ad:!0,action:!0});function H(a){var c="amp-auto-lightbox-carousel";if(a.__AMP__EXPERIMENT_TOGGLES)var b=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);b=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(b[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]'))){e=
e.getAttribute("content").split(",");for(var f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(b[e[f]]=!0)}Object.assign(b,I(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(d=a.AMP_CONFIG["allow-url-opt-in"],a=n(a.location.originalHash||a.location.hash),e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(b[d[e]]=!0),"0"==f&&(b[d[e]]=!1)}var g=b;return!!g[c]}
function I(a){a:{try{var c=a.document.cookie}catch(g){c=""}if(a=c)for(a=a.split(";"),c=0;c<a.length;c++){var b=a[c].trim(),d=b.indexOf("=");if(-1!=d&&"AMP_EXP"==l(b.substring(0,d).trim(),void 0)){a=b.substring(d+1).trim();a=l(a,a);break a}}a=null}var e=a,f=e?e.split(/\s*,\s*/g):[];a=Object.create(null);for(c=0;c<f.length;c++)0!=f[c].length&&("-"==f[c][0]?a[f[c].substr(1)]=!1:a[f[c]]=!0);return a};function J(a){if("a"==a.tagName.toLowerCase()&&a.hasAttribute("href")||a.querySelector("a[href]"))return!0;var c=w(a,"action"),b=c.hasResolvableAction(a,"tap",a.parentElement);if(b)return!0;var d=a.querySelectorAll("[on]");for(a=0;a<d.length;a++){var e=d[a];if(c.hasResolvableAction(e,"tap",e.parentElement))return!0}return!1};function K(){return k(function(){return!1})}function L(){return k(function(){return!0})};function M(a){if(!H(a.ownerDocument.defaultView))return K();var c=a.querySelectorAll(".amp-carousel-slide"),b=a.querySelectorAll("amp-img");if(1>b.length||c.length!=b.length)return K();var d=L();F(c,function(a){d=d.then(function(b){return b?N(a):!1})});return d}function N(a){if("AMP-IMG"==a.tagName)return k(function(){return!J(a)});var c=a.querySelector("amp-img");if(!c)return K();var b=O(c,a);return b.then(function(b){return b?!J(a):!1})}
function O(a,c){return a.getImpl().then(function(b){return new Promise(function(d){b.measureElement(function(){var b=a.getLayoutBox(),f=b.width,g=b.height;b=c.getBoundingClientRect();var q=b.width,R=b.height,S=f*g,T=q*R;d(.5<=S/T)})})})};var P={Article:!0,NewsArticle:!0,BlogPosting:!0,LiveBlogPosting:!0,DiscussionForumPosting:!0},Q=["amp-img","amp-carousel"];function U(){}
function V(a){if("AMP-IMG"==a.tagName.toUpperCase()){var c=a.querySelector("img");var b=c.naturalWidth;c=c.naturalHeight;var d=a.getLayoutBox(),e=d.width;d=d.height;var f=z(a);f=A(f);var g=y(f,"viewport").getSize();f=g.width;g=g.height;e*=d;b=1.2<=b*c/e||b>f||c>g||.25<=e/(f*g)}else b=!0;b&&(b=(b=D(a))&&(b!=a||E(b,"[placeholder],[data-amp-auto-lightbox-disable],amp-selector [option],[subscriptions-action]"))?!1:!w(a,"action").hasResolvableAction(a,"tap"));return b?"AMP-CAROUSEL"==a.tagName.toUpperCase()?
M(a):L():K()}function W(a){return X(a,function(){a.setAttribute("i-amphtml-auto-lightbox-visited","")})}function Y(a){return a+":not([lightbox]):not([i-amphtml-auto-lightbox-visited])"}function aa(a){return G(a).then(function(a){return a.signals().whenSignal("load-end")})}function ba(a){return t(a.getRootNode().querySelectorAll('script[type="application/ld+json"]')).map(function(a){var b=a.textContent;try{var c=JSON.parse(b)}catch(e){c=null}return(c||{})["@type"]}).filter(function(a){return a})}
function ca(a){return ba(a).some(function(a){return P[a]})}function X(a,c){return G(a).then(function(a){return a.getResources().mutateElement(a,c)})}function da(a){function c(b){return!!a.getRootNode().querySelector(b)}var b='script[custom-element="amp-lightbox-gallery"]',d="[lightbox]:not([i-amphtml-auto-lightbox-visited])";return c(b)&&c(d)}var ea=0;
function fa(a,c){return X(c,function(){c.setAttribute("lightbox","i-amphtml-auto-lightbox-"+ea++)}).then(function(){B(a.win,"extensions").installExtensionForDoc(a,"amp-lightbox-gallery");c.dispatchCustomEvent("amp-auto-lightbox:newly-set");return c})}function ha(a,c){c.map(function(b){return aa(b).then(function(){return V(b).then(function(c){if(c)return v().info("amp-auto-lightbox","apply",b),fa(a,b)})},U)})}
function Z(a,c){var b;(b=da(a))||(b=(b=a.getRootNode().querySelector('meta[property="og:type"]'))?b.getAttribute("content"):void 0,b="article"!=b&&!ca(a));if(b)b=!1;else if(b=a.win,r(b).localDev&&!r(b).test)b=!0;else{var d=a.getBody().firstElementChild;b=d?w(d,"url").isProxyOrigin(b.location):!1}b?(b=c||a.win.document,d=Q.map(Y).join(","),b=t(b.querySelectorAll(d)),b.forEach(W),ha(a,b)):v().info("amp-auto-lightbox","disabled")}
(function(a){var c=a.ampdoc;c.whenReady().then(function(){c.getRootNode().addEventListener("amp:dom-update",function(a){Z(c,a.target)});Z(c)})})(self.AMP);
})});

//# sourceMappingURL=amp-auto-lightbox-0.1.js.map
